### ISSUE TITLE
Implementation on Azure Devops pipeline

### ISSUE THREAD

**Issue by isabr85** [pmowrer/semantic-release-monorepo#102]
I really like the idea behind this solution and would like to implement it as part of our CD process in Azure pipeline.
Unfortunately, I couldn't find any explanation about how to do it.

The root directory of the repository contains:
* ProjectA folder
* ProjectB folder
* releaserc.js configuration file.

Is the structure and and the position of releaserc.js file are correct?
How that bash scripts within the CD pipeline should be look like?
Thanks.

**Comment by pmowrer** [comment]
Sorry, this isn't a forum for general support working with `semantic-release`. If you have an issue specific to `semantic-release-monorepo`, feel free to bring that up
