### ISSUE TITLE
Allow read-pkg to be higher major version to fix Yarn 2.0 issues

### ISSUE THREAD

**Issue by yinzara** [pmowrer/semantic-release-monorepo#104]
When using Yarn 2.0 with semantic-release-monorepo, an error occurs when attempting to execute `readpkg.sync()` 

This is because the version of read-pkg (3.0.0) is very out of date (more than 3 years old) and breaks with yarn 2.0. 

Could you upgrade to a newer version? Even upgrading to version 4.0.0 would correct the issue.  If you did this, it would mean semantic-release-monorepo would require at least NodeJS 6.0 as read-pkg 4.0.0 requires Node 6.  read-pkg v3.0.0 requires NodeJS 4 so you're not really adding much of a restriction.

If you're not willing to add that restriction, could you at least change the package dependency to ">=3.0.0" instead of "^3.0.0" so that projects that depend on this with yarn 2.0 continue to function?

**Comment by pmowrer** [comment]
Upgraded to most recent 5.x. Hope it works!
