### ISSUE TITLE
Yarn 2 support

### ISSUE THREAD

**Issue by johngeorgewright** [pmowrer/semantic-release-monorepo#107]
[Yarn2]: https://yarnpkg.com/

I've just tried your plugin with [Yarn2][]'s workspaces, however I have reached a stumbling point.

By default [Yarn2][]'s workspaces will add linked dependencies by prefixing their version with `workspace:`:

```json
{
  "dependencies": {
    "foo": "workspace:*",
    "bar": "workspace:^1.2.3",
    "baz": "workspace:path/to/baz"
  }
}
```

Then, [according to their documentation](https://yarnpkg.com/features/workspaces#publishing-workspaces), when running the publishing command, the version is replaced with what it can find in the mono-repo.

As semantic release doesn't use yarn's publishing command, these don't get replaced and the version is published to NPM as `workspace:*`. **Could this monorepo plugin help solve the problem?**.

**Comment by pmowrer** [comment]
Hi @johngeorgewright! The scope of this library is limited to augmenting `semantic-release` by applying its behavior across a monorepo. In `semantic-release` land, new behaviors are typically introduced through plugins. E.g. `npm` is supported through the `@semantic-release/npm` plugin. I would think a `@semantic-release/yarn` plugin would be the appropriate place for this logic to live, as suggested in https://github.com/semantic-release/npm/issues/382.

All that said, I've yet to migrate to yarn2 so I can't say I'm familiar with this workflow. Feel free to reopen if you can help explain further why this belongs in `semantic-release-monorepo` vs a separate plugin.

**Comment by Rotorsoft** [comment]
Hi @pmowrer, I'm facing the same yarn2 mono-repo issue described here and was wondering if you already found a workaround? Everything works beautifully until it gets to the npm prepare step 

stderr: 'npm ERR! code EUNSUPPORTEDPROTOCOL\n' +
➤ YN0000:     'npm ERR! Unsupported URL Type "workspace:": workspace:^0\n' +

thank you!

**Comment by alvarlagerlof** [comment]
Yeah I am getting that too. Is this just a scanning issue or bigger. It should not really look at this dependency at all since it is an example folder.
`Unsupported URL Type "workspace:": workspace:1.0.0-semantic-release`

**Comment by alvarlagerlof** [comment]
> Created a couple of GitHub actions to deal with yarn monorepos semrel-analyze and semrel-release

Do you have a pointer?

**Comment by Rotorsoft** [comment]
https://github.com/Rotorsoft/semrel-release/releases
