### ISSUE TITLE
is there support for maintanance branches for each workspace separately ?

### ISSUE THREAD

**Issue by articot** [pmowrer/semantic-release-monorepo#108]
e.g. I have two workspaces - `workspace-a`, `workspace-b`

out of the box `semantic-release` allows for creating maintenance branches e.g. `1.x.x`, `1.1.x`, but what if I want separate branches for each workspace:  `workspace-a.1.x.x`, `workspace-b.1.x.x`

is there a way to support it ?

**Comment by pascalporedda** [comment]
Yeah I've been wondering about this as well.

Since I could not get the maintenance branches to work _at all_ with this.

**Comment by pmowrer** [comment]
Hi @articot! Does `semantic-release` support this? If not, that would be the first place to ask.
