### ISSUE TITLE
[Feature Request] Please support global plugin configurations

### ISSUE THREAD

**Issue by latipun7** [pmowrer/semantic-release-monorepo#110]
## Tools Info

semantic-release: v17.4.4,
semantic-release-monorepo: v7.0.5

## Problem

Hi @pmowrer , thanks for this tools. It's really great and helpful.

Since as of `semantic-release` v17.4.4, there's a feature for [global plugin configurations](https://semantic-release.gitbook.io/semantic-release/usage/plugins#plugin-options-configuration), so I'd like to request that this tools support global plugin configurations too.

As of now, if I have config like this:
```js
module.exports = {
  extends: ['semantic-release-monorepo'],
  branches: ['main'],
  plugins: [
    [
      '@semantic-release/commit-analyzer',
      {
        preset: 'conventionalcommits',
        presetConfig: {
          types: [
            { type: 'feat', section: '✨ Features' },
          ],
        },
      },
    ],
    [
      '@semantic-release/release-notes-generator',
      {
        preset: 'conventionalcommits',
        presetConfig: {
          types: [
            { type: 'feat', section: '✨ Features' },
          ],
        },
      },
    ],
    [
      '@semantic-release/changelog',
      {
        changelogFile: 'changelog.md',
    ],
    '@semantic-release/npm',
    [
      '@semantic-release/git',
      { /** truncated */ },
    ],
    '@semantic-release/github',
  ],
};
```
it would pick the configurations as expected.
But that would unefficient because there's repeated code/config.

If I try to use valid global plugin configurations with this monorepo tools:
```js
module.exports = {
  extends: ['semantic-release-monorepo'],
  branches: ['main'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/changelog',
      {
        changelogFile: 'changelog.md',
    ],
    '@semantic-release/npm',
    [
      '@semantic-release/git',
      { /** truncated */ },
    ],
    '@semantic-release/github',
  ],
  preset: 'conventionalcommits',
  presetConfig: {
    types: [
      { type: 'feat', section: '✨ Features' },
    ],
  },
};
```
this tool didn't picked up the plugins configurations that would fallback to the default config which is not what I expected.

Please support global plugin configurations too.
Thank you.

**Comment by pmowrer** [comment]
Makes sense! This lib aims to provide feature-parity with `semantic-release`. I'll look into this soon... thanks for the heads up @latipun7!

**Comment by GuyLescalier** [comment]
Hi,
The issue actually comes from `semantic-release-plugin-decorators` (https://github.com/pmowrer/semantic-release-plugin-decorators).
I just made a PR.

**Comment by JoCa96** [comment]
The PR  was merged, but no new version was released.
As this repo doesn't seem to be active anymore, I published a version "7.0.6" myself with this feature/fix.
Should anybody need it you can find it here: https://www.npmjs.com/package/@joca96/semantic-release-monorepo

**Comment by borisdamevin** [comment]
@pmowrer Possible to make a release plz?

Thank you!

**Comment by jdbruijn** [comment]
I'm running into this as well now @pmowrer would it be possible to make a npm release of the  latest master, please? Happy to help if there is anything I can do.

**Comment by pmowrer** [comment]
This project used to built using Travis CI but that platform no longer seems to be working. Need to get the build process migrated to github actions

**Comment by iugabogdan** [comment]
any news on this guys ? I can help migrating to github actions.
