### ISSUE TITLE
No independant lerna config?

### ISSUE THREAD

**Issue by borisdamevin** [pmowrer/semantic-release-monorepo#115]
Hi,

I don't see _(or understand)_ if the plugin work with global version lerna config instead of `independant` configuration.

This possiblity exist? @pmowrer 

Thank you.

**Comment by borisdamevin** [comment]
@pmowrer :)

**Comment by pmowrer** [comment]
I'm alive! Sorry, haven't had any time to dedicate to open source recently. I think a fix was merged into the supporting `semantic-release-plugin-decorators` library and maybe it just needs to be bumped? Would you be able to verify @borisdamevin?
