### ISSUE TITLE
get the releasing workspace

### ISSUE THREAD

**Issue by eng-dibo** [pmowrer/semantic-release-monorepo#122]
how to get a reference to the current workspace being released

for example I want to add this reference to `@semantic-release/git` `options.message` like this:

```
["@semantic-release/git",{
  message: 'build releasing $workspace'
}
]
```

**Comment by pmowrer** [comment]
The git plugin has a [preset list of interpolated variables](https://github.com/semantic-release/git#message). You'd have to extended it to support a "workspace" variable, but you'd have to look into whether that's possible. Feel free to reopen if you have any ideas about how this could be implemented.
