### ISSUE TITLE
[Bug]: analyzeCommits doesn't run monorepo login on newer commit

### ISSUE THREAD

**Issue by yarinsa** [pmowrer/semantic-release-monorepo#127]
Expected: 
 AnalyzeCommit will determine a new version if there is no version deployed since the last tag for the package and there are changes. 
 AnalyzeCommit will a new version if there is no changes exist in newer since the last tag for the package and there are changes. 

Actual:
` The local branch develop is behind the remote one, therefore a new version won't be published.`

Will be willing to help with some guidance, thanks!

**Comment by yarinsa** [comment]
Yep, but lets demonstrate a use case:
I have 3 "new packages" to release
1. First package published and commits on develop
2. Second package publish (will already report that a new commit has been found on branch)
3. Third package publish (will already report that a new commit has been found on branch)

My workaround is to checkout the latest commit every-time, and not run those tasks in parallel

**Comment by jcapogna** [comment]
@yarinsa I ran into the same problem. A single commit triggers a multi-stage pipeline, with each stage releasing a different package. Only my first stage succeeds for the same reason you're outlining above.

I ended up doing the same workaround of having each release step checkout the latest commit. 

In GitLab CI/CD I setup a before_script task:
```
    before_script:
        - git checkout $CI_COMMIT_BRANCH
```

**Comment by pmowrer** [comment]
Per @travi's comment, this is how `semantic-release` works. Good workaround @jcapogna!
