### ISSUE TITLE
ERR_REQUIRED_ESM error with multiple plugin packages

### ISSUE THREAD

**Issue by jcapogna** [pmowrer/semantic-release-monorepo#138]
It has been documented in a few places like #136 that certain semantic-release plugins need to be downgraded when using semantic-release-monorepo, due to it not support ESM yet. ESM support should be added in #137. 

I'm creating this ticket to consolidate knowledge about this problem for other people. 

So far I have to add perform the following downgrades:
* @semantic-release/commit-analyzer to v9
* @semantic-release/gitlab to v9
* @semantic-release/npm to v9

**Comment by FrederickEngelhardt** [comment]
Same problem. Thanks for making this issue.

**Comment by JosefSaltz** [comment]
Confirming that I also only get this error when using semantic-release-monorepo. When I remove the `extends:` line from my .releaserc.json my workflow runs as expected.

**Comment by bryanjtc** [comment]
I published a new package [semantic-release-monorepo-esm](https://www.npmjs.com/package/semantic-release-monorepo-esm) that supports esm. v1.0.10 should work without issues.

**Comment by jcapogna** [comment]
@bryanjtc That's awesome. I was thinking it might make sense to fork this. I'll play around with it.

**Comment by mario-jerkovic** [comment]
@jcapogna 
We've released a monorepo package that's compatible with ESM, and since you have access to the source code, you're free to customize it as you wish. Cheers! 🍻

**NPM package:** https://www.npmjs.com/package/@rimac-technology/semantic-release-monorepo
**Source code:** https://github.com/RimacTechnology/semantic-release-monorepo

**Comment by jcapogna** [comment]
@mario-jerkovic That's great! I'll check it out. 

@pmowrer If one of these forked packages works well, maybe we should deprecate this package and point it to the fork since this package is no longer maintained.

**Comment by mario-jerkovic** [comment]
> @mario-jerkovic That's great! I'll check it out.
> 
> @pmowrer If one of these forked packages works well, maybe we should deprecate this package and point it to the fork since this package is no longer maintained.
> 
> Are there any major differences between [semantic-release-monorepo-esm](https://www.npmjs.com/package/semantic-release-monorepo-esm) from @bryanjtc and https://github.com/RimacTechnology/semantic-release-monorepo from @mario-jerkovic ??

This package is a rewrite and should be drop-in replacement, only difference is that the default tag format is `pacakge-name@version` but you can override it by defining `tagFormat`key in .releaserc everything else should work the same  🙂
