### ISSUE TITLE
@semantic-release/github adds comments to the wrong issues

### ISSUE THREAD

**Issue by stalniy** [pmowrer/semantic-release-monorepo#51]
It looks like `@semantic-release/github` adds comments to the wrong issues when used in monorepo

**Comment by pmowrer** [comment]
I think you're right! Haven't had a chance to look into it. Here's a few related issues:

https://github.com/semantic-release/github/issues/50
https://github.com/semantic-release/github/issues/63

Help wanted!

**Comment by pmowrer** [comment]
As a temporary workaround, the comments can be turned off by overriding the default `success` and `fail` plugins (e.g. set them to empty arrays) in the release configuration

**Comment by stalniy** [comment]
I did some investigation and see that `github/success` function receives `context.commits` and that array of commits are not filtered by `semanatic-release-monorepo`.

Will try to understand why is that

**Comment by stalniy** [comment]
`semantic-release` looking for all commits starting until last release:

```js
  const commits = await getCommits(lastRelease.gitHead, options.branch, logger);
```

Later it passes this array of commits to every plugin call, in `options.commits`. That's why github plugin receives the list of all commits, parses them and send comments to wrong issues.

**Comment by milesj** [comment]
Has there been an update on this? It's pretty noise right now every time a release happens.

**Comment by cpinnix** [comment]
@milesj I don't have an update for you at the moment. But we will be looking into this in the next week or so.

**Comment by milesj** [comment]
Our releases are taking longer and longer because it's adding so many commits to PRs. If someone can point me to the location of what to fix, I can take a stab at it. Maybe wrapping the success plugin?

**Comment by prisis** [comment]
Is there a way to help you?

**Comment by pmowrer** [comment]
I have a branch up that should fix this, `github-comments-fix`, if anyone's willing to give it a try.

**Comment by GitGangGuy** [comment]
Has anyone tried this? Can we get this fixed in the package?

**Comment by stalniy** [comment]
Just FYI: 

I switched  to solution https://github.com/semantic-release/semantic-release/issues/193#issuecomment-578436666

Similar hack but is much simpler and augments only single package. Haven’t tried to enable release comments however. Better cross-release support

**Comment by GitGangGuy** [comment]
> Just FYI:
> 
> I switched to solution [semantic-release/semantic-release#193 (comment)](https://github.com/semantic-release/semantic-release/issues/193#issuecomment-578436666)
> 
> Similar hack but is much simpler and augments only single package. Haven’t tried to enable release comments however. Better cross-release support

You should check out [semantic-release-plus](https://github.com/semantic-release-plus/semantic-release)! Should be essentially the same, but it’s always kept up to date with semantic-release itself.

**Comment by travi** [comment]
> I have a branch up that should fix this, github-comments-fix, if anyone's willing to give it a try.

@pmowrer i've been testing this branch out a fair amount today, and it seems to be working as i would expect. what would it take to include this in a published release (even a pre-release would be ok with me)?

**Comment by pmowrer** [comment]
Thanks so much for trying it out @travi! That's good enough for me... just published a new release with the fix!

**Comment by travi** [comment]
thanks!
