### ISSUE TITLE
monorepo cross-dependencies

### ISSUE THREAD

**Issue by AVVS** [pmowrer/semantic-release-monorepo#67]
Hey, this is just a question, would appreciate the help

Imagine the scenario where we have a monorepo and packages depend on each other
lets say they are to be updated at the same time and they are all at version 0.0.1

Lets assume we have packages A,B,C

A
  depends on B,C
B depends on C

A is updated to version 1.0.0 with B,C deps 0.0.1
B updated to 1.0.0 with C dep 0.0.1
C updated to 1.0.0

Do i need to then perform another round of updates where B is updated to 1.0.1 with correct C dependency and then A is updated to new B and new C dependency?

Or the deps are resolved automatically and their versions are updated automatically and then lock files are also correctly updated?

If not - is there any approach that I should adopt to avoid the scenario above?
Thanks for all the help and sorry if the question sounds confusing, but I do hope I've described it in a more or less clear way

**Comment by cspotcode** [comment]
I've been giving this some thought.  It would be nice for a tool (`prepare-version-bumps`?) to analyze the dependency graph, then prompt the user for what to do with each dependency.

The desired workflow is:
1. engineer finishes their pull request; ready to merge.
2. engineer runs `prepare-version-bumps` locally.
3. Tool prompts engineer to answer questions about dependency bumps.  Tool commits, pushes to PR, and (optionally) merges PR.
3. semantic-release-monorepo publishes all packages with desired version bumps, reading data from the tool.

A sample prompt:

```
"foo" depends on "bar"
"foo" is version 3.4.5
Depends on bar ^1.0.1
"bar" will publish due to code changes. 1.0.1 -> 1.1.0
What should we do?
  1. leave "foo" alone
  2. update "foo" to the new version of "bar".  This is a breaking change for "foo"
  3. update "foo" to the new version of "bar".  This is a feature change for "foo"
  4. update "foo" to the new version of "bar".  This is a patch change for "foo"
What do you want to do? <1-4>: 2

Describe the change: updates to newest version of "bar", which changes return value of the yaddaYadda function
```

The answers to these questions are written to a file and committed to git.  semantic-release-monorepo uses it to bump dependencies during the release process, generating the correct changelog entries.

@pmowrer what do you think?  The level of complexity does not seem too high.
