### ISSUE TITLE
Help with old Lerna repository

### ISSUE THREAD

**Issue by leofavre** [pmowrer/semantic-release-monorepo#68]
This issue is actually a doubt that I could not resolve reading the documentation.

At work, we have a [Lerna-based monorepo](https://github.com/stone-payments/sling-web-framework) in which packages are versioned and released manually. When we tried to start using semantic-release-monorepo, the script assumed that the versions of our packages should begin at 1.0.0, but we already have some releases.

Is it possible to "tell" semantic-release-monorepo the current versions of our packages so that it starts from there?

By the way, I was able to successfully use semantic-release-monorepo [in a project](https://github.com/leofavre/memory-game-elements) in which it was installed from the very beginning.

**Comment by egucciar** [comment]
I think so. From what i see, the plugin works by searching in the commit tree for tags. It knows what the last release is based on the tags alone. You can manually add a tag that corresponds to your release.

![image](https://user-images.githubusercontent.com/2848185/48232632-405dac80-e380-11e8-9aa2-757186d1ca4c.png)

this is an example tag produced within our mono repo. It looks like it does `packageName-version`. So tag your master/main branch with that same convention, let me know it it works.

**Comment by leofavre** [comment]
@egucciar Thank you, I'll try that soon.
