### ISSUE TITLE
semantic release 16 support

### ISSUE THREAD

**Issue by alexan** [pmowrer/semantic-release-monorepo#70]
Hi,
I just wanted to ask if this package will get semantic release 16 support. Which will add support for prelease and bugfix releases on different branches. Which will most likely not work out of the box with monorepos.
Do you need any help with doing so?

**Comment by julrich** [comment]
Did you ever figure this out @alexan? Will have a go at this, too. We kind of need bugfix and prerelease support for our development workflow!

**Comment by pmowrer** [comment]
This library should now work with `semantic-release` v15.11 and above as of [v7.0.0](https://github.com/pmowrer/semantic-release-monorepo/releases/tag/v7.0.0). I'm not intimately familiar with the new release workflows, but my initial impression is it should work out-of-the-box. Please re-open if it doesn't.
