### ISSUE TITLE
create a prerelease of one package with monorepo?

### ISSUE THREAD

**Issue by scottnath** [pmowrer/semantic-release-monorepo#72]
Is there a way to create a prelease version of a specific package with monorepo?

I'd like to run `semantic-release` to release one of my packages on a branch where we're building our next release version.

Does anyone have an example of doing this?

**note**: I'm aware of version 16x of `semantic-release` but so far it's been buggy and I haven't been able to get the latest version to do what I want - so specifically looking for 15x solutions please.

thank you!

**Comment by albertoig** [comment]
Any chance to update this project with 16x versions? 

Thanks!

**Comment by pmowrer** [comment]
Version 16 and above should be supported as of [v7.0.0](https://github.com/pmowrer/semantic-release-monorepo/releases/tag/v7.0.0).
