### ISSUE TITLE
Possible to set lastRelease?

### ISSUE THREAD

**Issue by snebjorn** [pmowrer/semantic-release-monorepo#84]
I have an existing repo that I'm converting into a monorepo. So there are already tags using the default format `v${version}`.

So when running with `-e semantic-release-monorepo` it cannot find any previous releases because it's looking for the wrong tag.

The `--tag-format` can't be used as I want the nextRelease to have the new format.

Log
```shell
[semantic-release] » √  Completed step "verifyConditions" of plugin "@semantic-release/git"
[semantic-release] » i  No git tag version found on branch master
[semantic-release] » i  No previous release found, retrieving all commits
[semantic-release] » i  Found 64 commits since last release
[semantic-release] » i  Start step "analyzeCommits" of plugin "[Function: ]"
[semantic-release] [[Function: ]] » i  Found 0 commits for package test-package since last release
[semantic-release] [[Function: ]] » i  Analysis of 0 commits complete: no release
```

**Comment by snebjorn** [comment]
Not sure why I didn't think of this. But a workaround is simply to create the correct tag where the previous release tag is.

**Comment by pmowrer** [comment]
Glad it worked out!
