### ISSUE TITLE
Does this also work with a config file in the root directory when using lerna?

### ISSUE THREAD

**Issue by GitGangGuy** [pmowrer/semantic-release-monorepo#90]
So, the readme is pretty scarce on this.
```
lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
```
Should I add semantic-release and semantic-release-monorepo to the devDependencies beforehand (as hinted by the `--no-install` flag) or are these dependencies installed with npx?  
Also, can I use a config file in my monorepo root directory instead of passing all configuration options as cli arguments like above?  
I'd appreciate some clarification. Thanks!

**Comment by pmowrer** [comment]
> Should I add semantic-release and semantic-release-monorepo to the devDependencies beforehand (as hinted by the --no-install flag) or are these dependencies installed with npx?

I believe this is addressed in the immediately following line in the README. Is this not clear? Could the language be improved? 
> Thanks to how npx's package resolution works, if the repository root is in $PATH (typically true on CI), semantic-release and semantic-release-monorepo can be installed once in the repo root instead of in each individual package, likely saving both time and disk space.

> Also, can I use a config file in my monorepo root directory instead of passing all configuration options as cli arguments like above?

By "config file", do you mean a `lerna` config file? Which CLI arguments were you hoping to eliminate?

**Comment by GitGangGuy** [comment]
First of all, thank you for replying! Maintaining open source projects for essentially nothing takes time and money that could go elsewhere, so I really appreciate your response.

> By "config file", do you mean a `lerna` config file? Which CLI arguments were you hoping to eliminate? 

I mean the ``.releaserc`/`release.config.js` file used to configure semantic-release. Can I just place one in my root directory (with the `extends `option etc in it) and then call semantic-release like so:
```
lerna exec --concurrency 1 -- npx --no-install semantic-release
```
Or do I have to pass all the options as command line arguments like in your example? (with the `-e` flag etc)  
Thanks in advance!

**Comment by pmowrer** [comment]
> I mean the ``.releaserc/release.config.js` file used to configure semantic-release. Can I just place one in my root directory (with the `extends `option etc in it)

I don't think so, because `semantic-release` looks for the config file relative to the current working directory (ie each package's root dir).

However, I think you should be able to put all your configuration in a release config file and then pass it via the `-e` flag.

**Comment by GitGangGuy** [comment]
Thanks again, I'll try that.
Unrelated to your plugin, I'd be very grateful if you could help me out a little with this question: Would you recommend using Git(hub) for a monorepo (in a small team) or should I use something like Perforce Helix Core or SVN (due to their higher efficiency with one large repo) instead? :pray:
I'll close this issue for now.

**Comment by pmowrer** [comment]
Sorry, don't think I can help you with that. I've never used Perforce, and SVN I haven't touched in 10+ years.
