### ISSUE TITLE
Question/issue how to manage updating local dependencies after versioning?

### ISSUE THREAD

**Issue by CHaNGeTe** [pmowrer/semantic-release-monorepo#92]
First, thanks for this extension.
I wanted to ask how to handle the updating of version numbers on local dependencies.

For example:
semantic-release detects a change on module-A(1.0.0) and releases module-A(1.0.1)
module-B has a dependency on module-A, but package.json still references module-a(1.0.0)

How to include that version bump on the module-B release?

**Comment by pmowrer** [comment]
It has to be handled manually. 

Unfortunately, automatic upgrading of depending packages arguably falls out of scope of what `semantic-release` has been intended to do. It's more likely in the domain of something like `lerna` or `greenkeeper`, but I'm not presently aware of any such fully baked solution. In fact, the maintainer of `semantic-release` has been staunchly opposed to supporting monorepos at all until a solution to this workflow has been proposed (prompting the creation of this workaround-plugin).

See this thread for more context: https://github.com/semantic-release/semantic-release/issues/193

**Comment by yyynnn** [comment]
@CHaNGeTe try multi-semantic-release
