### ISSUE TITLE
[QUESTION] How to customize config for @semantic-release/npm for each package?

### ISSUE THREAD

**Issue by vinverdy** [pmowrer/semantic-release-monorepo#95]

**Comment by vinverdy** [comment]
nvm, I will read the package name and change config depends on package name. maybe it should be documented?

**Comment by tamj0rd2** [comment]
Could you give an example of how you did it @vinverdy ? I'm trying to do the same thing

**Comment by vinverdy** [comment]
`const path = require('path');
const packagePath = process.cwd().split(path.sep).slice(-2).join(path.sep);

if(packagePath === 'bla/bla') {
  return config;
}
`

something like this @tamj0rd2
