### ISSUE TITLE
Nx: App not released when referenced lib has changed

### ISSUE THREAD

**Issue by rmeyergh** [pmowrer/semantic-release-monorepo#96]
I'm working in an Nx monorepo that contains a lib and an app. The app references the lib. When I change something in the lib a new release of the lib is triggered but not for the app. Is there a possibility to make semantic release realize it has to release a new version of the app as well when dependencies change?

**Comment by pmowrer** [comment]
This is an oft-requested feature but unfortunately not one that's in scope of this plugin. For more, see:

https://github.com/pmowrer/semantic-release-monorepo/issues/92
https://github.com/pmowrer/semantic-release-monorepo/issues/29
